services:
  backend:
    build: ./backend
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://oronamos4:Neba1234@cluster0.qkvsk.mongodb.net/
    depends_on:
      - mongo

  frontend:
    build: ./trading-app
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
